name: EssentialsSSH
main: com.salkcoding.essentialsssh.EssentialsSSH
version: 1.1.0-SNAPSHOT
description: Essentials by Salk_Coding
api-version: 1.19
authors: [Salk_Coding, Peulia]
depend:
  - Metamorphosis
  - BukkitLinked
commands:
  home:
    description: home
  setspawn:
    description: setspawn
  sethome:
    description: sethome
  spawn:
    description: spawn