name: EssentialsS
main: com.salkcoding.essentialsssh.EssentialsSSH
version: 1.0.0-SNAPSHOT
description: Essentials by Salk_Coding
api-version: 1.16
author: Salk_Coding
depend: [ KotlinBukkitAPI ]
commands:
  home:
    description: home
  setspawn:
    description: setspawn
  sethome:
    description: sethome
  spawn:
    description: spawn